mTvare6/hello-world.rs

Cargo.toml, src/main.rs, translations/en.json, translations/es.json
=> add spanish

Cargo.toml, README.md
All hail to the almighty to grant us the power to convert anything to memory safety.
=> Adding a failing build crate that is totally not c bindings. 

translations/fr.json
=> Add French

src/main.rs
=> Rewrite Rust

README.md
=> fixed numbering

src/main.rs
=> fix an oopsie woopsie

translations/la.json
=> added latin translation

src/main.rs
=> added latin to locales in main.rs

README.md
=> Beautified some lines

src/main.rs
=> Fix errors, add blank lines here and there for readability

Dockerfile
- [ N ] Does your pull request add a crate?
- [ 🚀] Does your pull request add a new language?
- [🚀 ] Is your pull request memory safe?
- [ 🚀] Is your pull request configurable?
- [ 🚀] Is your pull request minimal?
- [ 🚀] Is your pull request blazing fast?
```dockerfile
FROM rust:1.31
MAINTAINER 'mTvare6' <https://github.com/mTvare6/hello-world.rs>
LABEL maintainer="mTvare6"
LABEL memory_safe=true
WORKDIR /usr/src/hello-world
COPY . .
RUN cargo install --path .
CMD ["hello-world"]
ENTRYPOINT ["hello-world"]
```
=> Missing maintainer & `memory_safe=true` for indexing when searching. Switch to ENTRYPOINT to enhance augmentation.

hello-world.rs-buildscript
[Link to Shade](https://github.com/shade-linux/shade)
=> add buildscript for the shade package manager

PKGBUILD
***
* Using git+https is preverred over git:// according to Arch's packaging guidelines
* Added more CPU arch for building package on Archlinux32, Arch Linux ARM (no rust for arm [armv5] and i486)
=> pkgbuild revision

src/main.rs, translations/eo.json, translations/fr.json
=> Add support for eo

src/main.rs, translations/lj.json
=> Add support for lj

src/main.rs
=> Add safety comments.

src/main.rs
=> fix LANGUAGE_LOCALES type, avoid FTBFS

Cargo.toml, README.md, src/main.rs
the readme updated and now numbers are French
- #69 
- #75
=> bah-ouais-je-parle-français-très-couramment

README.md
This pull request adds installation instructions to the readme.
=> Add install steps 🚀

src/main.rs, translations/ro.json
=> Add Romanian support

.vscode/settings.json
I have improved the VSCode settings to improve `hello-world.rs` developers' productivity through a unified workflow.
=> Improve VSCode settings

Cargo.lock
https://github.com/rust-num/num-bigint/issues/218#issuecomment-912698626
=> Fix num-bigint compile error

src/main.rs
I've already fixed this in #89 though.
=> Fix the build error

src/main.rs
=> One more attempt to fix the build error

src/main.rs, translations/lt.json
=> added the lithuanian language🚀

flake.lock
=> update flake.lock 🚀

src/main.rs, translations/it.json
=> Add italian

src/main.rs, translations/no.json
=> add norwegian translation

.vimrc
what 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! …
=> add the vim RC !!

translations/fr.json
In French, exclamation points, question marks, colons, and semi-colons (all forms of "high" punctuation) should always have a space preceding them.
=> Fix French typo

translations/fr.json
Added a non breaking space before the exclamation point.
=> Fix french translations

src/main.rs, translations/is.json
- [🚀] Does your pull request add a new language?
- [🚀] Is your pull request memory safe?
- [🚀] Is your pull request configurable?
- [🚀] Is your pull request minimal?
- [🚀] Is your pull request blazing fast?
=> Adds blazing fast🚀 support for Icelandic (is) in memory-safe🚀🚀 rust(🚀)

src/main.rs, translations/my.json
=> add Malay translation

README.md
- [ 🚀] Does your pull request add a crate?
- [🚀 ] Does your pull request add a new language?
=> blazing🚀fast🚀🚀memory-safe🚀🚀🚀update (🚀)

PKGBUILD
cmake is a language
Cmake is sadly mostly written in c+++c :sob:
needed for glfw-sys crate
=> add cmake makedep

translations/dk.json
Add blazingly fast🚀🚀🚀 support for Danish in memory-safe rust(🚀)
=> Add blazingly fast🚀🚀🚀 support for Danish in memory-safe rust(🚀)

LICENSE.rs
- [🚀🚀🚀🚀🚀🔥🔥🔥🔥🔥] Is your pull request blazing fast?
This PR updates the wording of the Don't Ask Me About It License to allow use of the Software and extending provisions to the entire Software, patching CVE 🤢 allowing circumventing of license provisions applying to only one file. Additionally according to benchmarks LICENSE.rs is now 25% faster 🚀 and this PR clearly improves memory safety 🔥.
=> Update wording and permissions of the Don't Ask Me About It License

translations/cc.json
=> Add a translation in C

SECURITY.md
- [🚀] Does your pull request add a .md file?
- [🚀] Is your pull request memory safe?
- [🚀] Is your pull request configurable?
- [🚀] Is your pull request minimal?
- [🚀] Is your pull request blazing fast?
This adds a SECURITY.md policy, ensuring that rust is [🔒](https://emojipedia.org/emoji/%F0%9F%94%92/) locked [🔒](https://emojipedia.org/emoji/%F0%9F%94%92/) down to the [🔒](https://emojipedia.org/emoji/%F0%9F%94%92/) best possible capacity. Rust is already Secure [🔒](https://emojipedia.org/emoji/%F0%9F%94%92/) but `.md` files may have (C)VEs
which are bad.
=> Add a 🚀 (blazing) 🚀 fast security (lockdown) policy

Makefile
=> fix(makefile): typo
